version: '3.8'

services:

  tomcat:
    image: tomcat:9.0
    container_name: doctor_appointment_tomcat
    ports:
      - "8000:8080"
    volumes:
      - ./target/hms.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=appointments
      - DB_USER=root
      - DB_PASSWORD=admin

  db:
    image: mysql:8.0
    container_name: doctor_appointment_db
    restart: always
    environment:
      MYSQL_DATABASE: appointments
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
